services:
  softcalfut_back:
    image: node:20
    working_dir: /usr/src/app
    build: .
    container_name: softcalfut_api
    restart: always
    depends_on:
      - nats
      - redis
    ports:
      - ${PORT_API}:4000
    environment:
      - NODE_ENV=${env}
      - DB_HOST=${HOST_DB}  
      - DB_PORT=${PORT_DB}
      - DB_USER=${USER_DB}
      - DB_PASSWORD=${PASS_DB}
      - DB_NAME=${NAME_DB}
      - NATS_URL=nats://${NATS_HOST}:${NATS_PORT}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRETO}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_SALT=${JWT_SALT}
      - DB_URL=postgresql://${USER_DB}:${PASS_DB}@${HOST_DB}:${PORT_DB}/${NAME_DB}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - docker_app_network
    command: ["sh", "-c", "npm install && yes | npx prisma generate && npm run dev"]

  nats:
    image: nats:latest
    container_name: nats_server
    restart: always
    ports:
      - ${NATS_PORT}:4222
    networks:
      - docker_app_network
    
  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - docker_app_network
    volumes:
      - redis_data:/data
volumes:
  redis_data:

networks:
  docker_app_network:
    driver: bridge
