services:
  app:
    image: node:20
    working_dir: /usr/src/app
    build: .
    env_file:
      - .env
    container_name: inventario_app
    restart: always
    depends_on:
      - nats
      - redis
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=Dev
      - DB_HOST=psql  
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=ciro
      - DB_NAME=personal_inventary
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - docker_app_network
    command: ["sh", "-c", "npm install && yes | npx prisma generate && npm run dev"]

  nats:
    image: nats:latest
    container_name: nats_server
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - docker_app_network
    
  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - docker_app_network
    volumes:
      - redis_data:/data
volumes:
  redis_data:

networks:
  docker_app_network:
    external: true
